### ISSUE TITLE
Контент - реализовать ElementEditor

### ISSUE THREAD

**Issue by ivan-podgornov** [colibrijs/colibrijs#108]
Нужно реализовать компонент, который позволит редактировать пропсы элемента. По мере редактирования пропсов вызывается функция onEdit с новыми пропсами элемента. Так же, когда пользователь начал редактировать что-то, появляется галчонок, который позволяет сохранить изменения

Так же, должна быть кнопка для удаления элемента. Для неё уже есть компонент element-remove. В пропсы element-remove нужно передать onRemove, который пришел в пропсах element-editor.

```ts
interface Props {
  element: IElement;
  onRemove: () => void;
  onEdit: (newProps: object) => void;
}
```

<img width="376" alt="image" src="https://github.com/user-attachments/assets/ba93f4d1-d24a-4f33-97e4-428153f6a984">

**Comment by ivan-podgornov** [comment]
Сейчас у ContentEditor уже реализован ElementEditor, но на минималках. Оттуда можно взять базовую версию. https://github.com/colibrijs/colibrijs/blob/main/packages/core/components/content-editor/content-editor.tsx#L67-L82

**Comment by okovtkov** [comment]
Тесты.

**Props**:
- [x] При передаче isOpen пропса, модалка открыта
- [x] При клике на крестик, вызывается onClose пропс
- [x] element.props выводится в textarea по дефолту
- [x] Изменение в textarea ведут за собой тяжкие последствия в виде вызова onEdit пропса с передачей измененного объекта
- [x] Клик на мусорку в положительном исходе вызывает onRemove пропс

**Common**:
- [x] Кнопка-галчонок появляется в случае, если изначальные пропсы отличаются от редактированных
- [x] Клик по галчонку, в положительном исходе делает запрос на api.elements.patch с идом элемента и новыми пропсами
- [x] Клик по галчонку в случае ошибки выдаст попап с текстом ошибки
