### ISSUE TITLE
Контент - Интегрировать ElementAdd в ContentEditor

### ISSUE THREAD

**Issue by ivan-podgornov** [colibrijs/colibrijs#115]
Нужно интегрировать готовый компонент ElementAdd в ContentEditor. Нужно чтобы по клику на кнопку "Добавить", появлялся ElementAdd.

Когда ElementAdd отправит событие onReady, он передаст в этом событии данные для добавления элемента в контент. Нужно отправить эти данные в api (https://colibrijs.github.io/colibrijs/main/swagger/redoc-static.html#tag/elements/operation/ElementsController_post) и то что вернёт api отправить в пропс onChange компонента ContentEditor. Есть даже уже готовый метод для работы с elements/post - можно использовать вызвав useApi. Ориентироваться можно на компонент page-add: https://github.com/colibrijs/colibrijs/blob/main/packages/core/components/page-add/page-add.tsx

**Comment by baronin** [comment]
Написать тесты

- [x] Добавление элемента скрыто по умолчанию
- [x] Когда добавление элемента отменено, интерфейс добавления скрывается
- [x] Когда добавляется новый элемент, интерфейс добавления скрывается
- [ ] Если ни один из элементов не выбран, новый элемент добавляется в конец дерева
- [ ] Если один из элементов выбран, новый элемент добавляется после выбранного
