### ISSUE TITLE
Скриншотные тесты - научиться запускать джобу по http-запросу

### ISSUE THREAD

**Issue by okovtkov** [colibrijs/colibrijs#156]
Хотим научиться апрувить изменения в скриншотах. Но есть чёрные дыры в понимании этого процесса. Самая главная чёрная дыра заключается в том, что непонятно как тригерить джобы по http-запросу. Если научиться это делать, дальнейшие шаги полностью понятны.

Нужно научиться запускать джобы с помощью http-запросов. Для начала, нужно сделать джобу, которая просто выполняет echo "привет". После этого, нужно каким-то образом её запустить с помощью http-запроса

**Comment by okovtkov** [comment]
upd. Как запустить знаем.
Вот такой фетч запрос для этого нужен:
```ts
const owner = "colibrijs";
const repo = "colibrijs";
const workflowId = "screenshot-approve.yml"; // Название .yml файлика или его id. Хз что такое id, поэтому юзаю название
const PAT_TOKEN = "YOUR_PERSONAL_ACCESS_TOKEN"; // Наш персональный токен доступа, берется тут - https://github.com/settings/tokens

fetch(`https://api.github.com/repos/${owner}/${repo}/actions/workflows/${workflowId}/dispatches`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${PAT_TOKEN}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          ref: 'issue-156', // вот тут указывается наша ветка
        }),
      }
    );
```

**Comment by ivan-podgornov** [comment]
Дальше нужно собрать сторибук и добавить в панель скриншотную кнопку, которая будет делать запрос. Кнопку нужно показывать только если есть упавшие скриншотные тесты.

Сторибук собирается [тут](https://github.com/colibrijs/colibrijs/blob/main/.github/workflows/build.yml#L34). Нужно прокинуть в него в енвах ещё github token и так же название ветки. В качестве токена нужно использовать `${{ secrets.GH_TOKEN }}`. Ну а название ветки можно взять с `${{ steps.metadata.outputs.branch }}`.
