### ISSUE TITLE
Скриншотные тесты - поправить компонент screenshot-table

### ISSUE THREAD

**Issue by okovtkov** [colibrijs/colibrijs#165]
Сейчас компонент screenshot-table находится внутри .storybook/screenshot-panel и сделан он с использованием библиотеки antd. Это очень хорошее, мудрое и правильное решение, которое бесспорно заслуживает уважения. 
Но мы всё же решили, что сделаем этот компонент на дефолтных html-элементах, чтобы при использовании данного пакета (спойлер) в других приложениях, не приходилось подтягивать целую библиотеку antd ради одной таблицы

**Comment by ivan-podgornov** [comment]
Когда вот это будешь делать, сделай чтоб не клик по строке приводил к переходу на сторис, а кнопошку справа добавь, которая это делает. Так же, вместо path (скриншот 1), который хз зачем нужен пользователю, лучше выводить название компонента (если это возможно) и описание сториса (это возможно). Под описанием имею в виду вот это (скриншот 2)

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/03ca59ba-3a17-4285-812a-fcd2d1203b5b">

<img width="290" alt="image" src="https://github.com/user-attachments/assets/604fd5e8-041a-4b11-9982-ee4ba7ab130f">
